'compiler':
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**/*'
          - 'CMakeLists.txt'
          - '*.cmake'

'bootstrap':
  - changed-files:
      - any-glob-to-any-file:
          - 'src-bootstrap/**/*'

'std':
  - changed-files:
      - any-glob-to-any-file:
          - 'std/**/*'

'tests':
  - changed-files:
      - any-glob-to-any-file:
          - 'test/**/*'

'documentation':
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**/*'
          - 'media/specs/**/*'
          - 'AGENTS.md'
          - 'README.md'
          - 'SECURITY.md'

'ci':
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**/*'