version: 2
project_name: spice
builds:
  - main: ./.github/media/dummy.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: amd64
      - goos: darwin
        goarch: arm64
    hooks:
      post:
        - mv ./bin/spice-{{ .Os }}-{{ .Arch }}/spice{{ .Ext }} {{ .Path }}
dockers:
  - image_templates:
      - ghcr.io/spicelang/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64
      - ghcr.io/spicelang/spice:latest-amd64
      - chillibits/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64
      - chillibits/spice:latest-amd64
    dockerfile: Dockerfile
    skip_push: auto
    use: buildx
    goarch: amd64
    extra_files:
      - bin
      - std
    build_flag_templates:
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --platform=linux/amd64
  - image_templates:
      - ghcr.io/spicelang/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-aarch64
      - ghcr.io/spicelang/spice:latest-aarch64
      - chillibits/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-aarch64
      - chillibits/spice:latest-aarch64
    dockerfile: Dockerfile
    skip_push: auto
    use: buildx
    goarch: arm64
    extra_files:
      - bin
      - std
    build_flag_templates:
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --platform=linux/arm64
docker_manifests:
  - name_template: chillibits/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    image_templates:
      - chillibits/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64
      - chillibits/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-aarch64
    skip_push: auto
  - name_template: chillibits/spice:latest
    image_templates:
      - chillibits/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64
      - chillibits/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-aarch64
    skip_push: auto

  - name_template: ghcr.io/spicelang/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    image_templates:
      - ghcr.io/spicelang/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64
      - ghcr.io/spicelang/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-aarch64
    skip_push: auto
  - name_template: ghcr.io/spicelang/spice:latest
    image_templates:
      - ghcr.io/spicelang/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64
      - ghcr.io/spicelang/spice:{{ .Major }}.{{ .Minor }}.{{ .Patch }}-aarch64
    skip_push: auto
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - std
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
nfpms:
  - id: publish
    file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    maintainer: Marc Auberer <marc.auberer@chillibits.com>
    vendor: ChilliBits
    description: Spice programming language.
    homepage: https://www.spicelang.com
    license: MIT
    bindir: /usr/bin
    formats:
      - apk
      - deb
      - rpm
    dependencies:
      - build-essential
      - clang
      - lld
    contents:
      - src: std
        dst: /usr/lib/spice/std
release:
  name_template: v{{ .Tag }}
  prerelease: auto
  footer: |
    ## What to do next?
    - [Install Spice](https://www.spicelang.com/install/linux)
    - Visit [www.spicelang.com](https://www.spicelang.com) to test the new features
changelog:
  use: github
  filters:
    exclude:
      - Merge pull request
      - Merge branch
milestones:
  - close: true
    fail_on_error: false