# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: spice

builds:
  - main: ./.github/media/dummy.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      # Only offer amd64 support on Windows
      - goos: windows
        goarch: arm64
      # Only offer arm64 support on macOS
      - goos: darwin
        goarch: amd64
    hooks:
      post:
        - "mv ./bin/spice-{{ .Os }}-{{ .Arch }}/spice{{ .Ext }} {{ .Path }}"

dockers_v2:
  - images:
      - "chillibits/spice"
      - "ghcr.io/spicelang/spice"
    tags:
      - "{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "latest"
    labels:
      "org.opencontainers.image.description": "Spice programming language."
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.name": "{{ .ProjectName }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.source": "{{ .GitURL }}"
    annotations:
      "org.opencontainers.image.description": "Spice programming language."
    extra_files:
      - std

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - std
    format_overrides:
      - goos: windows
        formats: [ "zip" ]

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

nfpms:
  - id: publish
    file_name_template: "{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    maintainer: Marc Auberer <marc.auberer@chillibits.com>
    vendor: ChilliBits
    description: Spice programming language.
    homepage: https://www.spicelang.com
    license: MIT
    bindir: /usr/bin
    formats:
      - apk
      - deb
      - rpm
    dependencies:
      - build-essential
      - clang
      - lld
    suggests:
      - mold
    contents:
      - src: std
        dst: /usr/lib/spice/std

release:
  name_template: "v{{ .Tag }}"
  prerelease: auto
  footer: |
    ## What to do next?
    - [Install Spice](https://www.spicelang.com/install/linux)
    - Visit [www.spicelang.com](https://www.spicelang.com) to test the new features

changelog:
  use: github
  filters:
    exclude:
      - "Merge pull request"
      - "Merge branch"

milestones:
  - close: true
    fail_on_error: false