# Publish documentation
name: Publish documentation

on:
  push:
    branches:
      - main
      - docs/**
      - feature/**
      - fix/**
    paths:
      - docs/**
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup GitHub pages
        uses: actions/configure-pages@v6

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev pngquant
          pip install -r docs/requirements.txt

      - name: Build
        working-directory: docs
        run: zensical build --clean

      - name: Upload
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs/site

      - name: Deploy
        uses: actions/deploy-pages@v5
        id: docs
